server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: false
douban:
  api:
    mappings:
      book: 1001
    user-agent: PostmanRuntime/7.28.2
    search-url: https://www.douban.com/search?cat={searchType}&q={searchText}
    detail-url: https://book.douban.com/subject/{id}
    isbn-url: https://book.douban.com/isbn/{isbn}