server:
  port: 8085
spring:
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    enabled: false
douban:
  api:
    mappings:
      book: 1001
    search-url: https://www.douban.com/search?cat={searchType}&q={searchText}
    search-json-url: https://www.douban.com/j/search?start=0&cat={searchType}&q={searchText}
    detail-url: https://book.douban.com/subject/{id}
    isbn-url: https://book.douban.com/isbn/{isbn}